language: node_js

sudo: false

node_js:
  - v8
  - v9

git:
  depth: 1

script:
  - yarn lint
  - yarn coverage

after_script:
  - yarn add --dev coveralls
# - cat ./coverage/lcov.info | yarn coveralls

branches:
  only:
    - master
